### ISSUE TITLE
cannot install pixi problem

### ISSUE THREAD

**Issue by whgusdn321** [raceychan/learncpp_pdf#1]
Hello thanks for the good project! 

I'm using this project to download learncpp pdf file. However I have a problem during installation.

Environments: 
WSL2 ubuntu (Windows 10)

My installation typing/log:

root@DESKTOP-EG3AKUQ:/mnt/c/Users/HyunwooJo# cd desktop
root@DESKTOP-EG3AKUQ:/mnt/c/Users/HyunwooJo/desktop# cd learncpp_pdf/
root@DESKTOP-EG3AKUQ:/mnt/c/Users/HyunwooJo/desktop/learncpp_pdf# make install && make run
curl -fsSL https://pixi.sh/install.sh | bash ; pixi install
This script will automatically download and install Pixi (latest) for you.
Getting it from this url: https://github.com/prefix-dev/pixi/releases/latest/download/pixi-x86_64-unknown-linux-musl.tar.gz
The binary will be installed into '/root/.pixi/bin'
######################################################################## 100.0%
Updating '/root/.bashrc'
Please restart or source your shell.
/bin/sh: 1: pixi: not found
make: *** [makefile:2: install] Error 127
root@DESKTOP-EG3AKUQ:/mnt/c/Users/HyunwooJo/desktop/learncpp_pdf#

**Comment by raceychan** [comment]
> Hello thanks for the good project! 
> 
> 
> 
> I'm using this project to download learncpp pdf file. However I have a problem during installation.
> 
> 
> 
> Environments: 
> 
> WSL2 ubuntu (Windows 10)
> 
> 
> 
> My installation typing/log:
> 
> 
> 
> root@DESKTOP-EG3AKUQ:/mnt/c/Users/HyunwooJo# cd desktop
> 
> root@DESKTOP-EG3AKUQ:/mnt/c/Users/HyunwooJo/desktop# cd learncpp_pdf/
> 
> root@DESKTOP-EG3AKUQ:/mnt/c/Users/HyunwooJo/desktop/learncpp_pdf# make install && make run
> 
> curl -fsSL https://pixi.sh/install.sh | bash ; pixi install
> 
> This script will automatically download and install Pixi (latest) for you.
> 
> Getting it from this url: https://github.com/prefix-dev/pixi/releases/latest/download/pixi-x86_64-unknown-linux-musl.tar.gz
> 
> The binary will be installed into '/root/.pixi/bin'
> 
> ######################################################################## 100.0%
> 
> Updating '/root/.bashrc'
> 
> Please restart or source your shell.
> 
> /bin/sh: 1: pixi: not found
> 
> make: *** [makefile:2: install] Error 127
> 
> root@DESKTOP-EG3AKUQ:/mnt/c/Users/HyunwooJo/desktop/learncpp_pdf#

I just updated the repo and replace pixi with its absolute path in the makefile, you might now clone the repo again and it would be fixed.
