### ISSUE TITLE
"Error establishing a database connection" printed on the generated pdf

### ISSUE THREAD

**Issue by rahoolrawp** [raceychan/learncpp_pdf#3]
Issue identified:
1. getcontent() in class DownloadService failure : No error reported in CLI/logs
2. _html_to_pdf is called twice, one sequentially and then parallelly : i guess you forgot to delete the sequential loop and hence progress bar is not in sync and it gives an impression of being stuck at download
3. Again no error handling for _html_to_pdf  in class Application

Incomplete pdf and the issue not being communicated through CLI/logs is an issue.

I have a fix for all the mentioned issue. Please let me raise a PR for the same.

Issue:
![image](https://github.com/user-attachments/assets/5b9cd513-67bb-4040-8ac4-9be6506d698a)

**Comment by raceychan** [comment]
submit your PR and i'll take look.

the error establishing a database connection should be returned by the server, which means if you just want to make it work you might make a retry.

**Comment by rahoolrawp** [comment]
@raceychan  Raised a PR : https://github.com/raceychan/learncpp_pdf/pull/4
Please review. I have added all the details in the PR along with test notes.
